version: '3'
services:
  indexjs-service:
    build: .
    ports:
      - "3002:3002"  # Ajusta el puerto para las métricas
    networks:
      - localprom

  prometheus:
    image: prom/prometheus
    ports:
      - 9091:9090
    volumes:
      - ./prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    depends_on:
      - indexjs-service

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - localprom
    depends_on:
      - prometheus

networks:
  localprom:
    driver: bridge
